http:
  serversTransports:
    wso2-transport:
      insecureSkipVerify: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/selfsigned.crt
        keyFile: /etc/traefik/certs/selfsigned.key
  certificates:
    - certFile: /etc/traefik/certs/selfsigned.crt
      keyFile: /etc/traefik/certs/selfsigned.key
